(grammar
  (start value)
  (tokens STRING NUMBER TRUE FALSE NIL
         LBRACE RBRACE LBRACKET RBRACKET COLON COMMA)
  (rules
    (value (STRING)
      action (lambda (value) (list 'string value)))
    (value (NUMBER)
      action (lambda (value) (list 'number value)))
    (value (TRUE)
      action (lambda (value) #t))
    (value (FALSE)
      action (lambda (value) #f))
    (value (NIL)
      action (lambda (value) 'null))
    (value (object)
      action (lambda (value) value))
    (value (array)
      action (lambda (value) value))
    (object (LBRACE members RBRACE)
      action (lambda (open content close) (list 'object content)))
    (object (LBRACE RBRACE)
      action (lambda (open close) (list 'object '())))
    (members (members COMMA member)
      action (lambda (rest comma item) (append rest (list item))))
    (members (member)
      action (lambda (item) (list item)))
    (member (STRING COLON value)
      action (lambda (key colon item) (cons key item)))
    (array (LBRACKET elements RBRACKET)
      action (lambda (open content close) (list 'array content)))
    (array (LBRACKET RBRACKET)
      action (lambda (open close) (list 'array '())))
    (elements (elements COMMA value)
      action (lambda (rest comma item) (append rest (list item))))
    (elements (value)
      action (lambda (item) (list item)))))
