;;; self contained lalr(1) parser generator
;;;
;;; grammar: (grammar (start expr) (tokens ID PLUS)
;;;   (precedence (left PLUS))
;;;   (rules (expr (expr PLUS ID) prec PLUS) (expr (ID))))
;;;
;;; input tokens are (token . value) pairs and rule actions are scheme procedures
;;; supplied with the action option and receive rhs values from left to right

(define lolly-version "0.1.0")

(define (lolly-filter p xs)
  (let loop ((xs xs) (out '()))
    (if (null? xs) (reverse out)
        (loop (cdr xs) (if (p (car xs)) (cons (car xs) out) out)))))
(define (lolly-any p xs)
  (cond ((null? xs) #f) ((p (car xs)) #t) (else (lolly-any p (cdr xs)))))
(define (lolly-all p xs)
  (if (null? xs) #t (and (p (car xs)) (lolly-all p (cdr xs)))))
(define (lolly-assoc k xs)
  (cond ((null? xs) #f) ((equal? k (car (car xs))) (car xs))
        (else (lolly-assoc k (cdr xs)))))
(define (lolly-ref k xs default)
  (let ((x (lolly-assoc k xs))) (if x (cdr x) default)))
(define (lolly-put k v xs)
  (cons (cons k v) (lolly-filter (lambda (x) (not (equal? k (car x)))) xs)))
(define (lolly-set-add x xs) (if (member x xs) xs (cons x xs)))
(define (lolly-union a b)
  (if (null? a) b (lolly-union (cdr a) (lolly-set-add (car a) b))))
(define (lolly-index x xs)
  (let loop ((xs xs) (n 0))
    (cond ((null? xs) #f) ((equal? x (car xs)) n)
          (else (loop (cdr xs) (+ n 1))))))
(define (lolly-subset a b) (lolly-all (lambda (x) (member x b)) a))
(define (lolly-fold-left f seed xs)
  (if (null? xs) seed (lolly-fold-left f (f seed (car xs)) (cdr xs))))
(define lolly-build-states '())
(define lolly-build-transitions '())

(define (lolly-reachable-symbols start rules)
  (let loop ((pending (list start)) (seen '()))
    (if (null? pending) seen
        (let ((symbol (car pending)))
          (if (member symbol seen)
              (loop (cdr pending) seen)
              (let ((children
                     (let scan ((rs rules) (out '()))
                       (if (null? rs) out
                           (if (eq? (vector-ref (car rs) 0) symbol)
                               (scan (cdr rs) (lolly-union (vector-ref (car rs) 1) out))
                               (scan (cdr rs) out))))))
                (loop (append children (cdr pending)) (cons symbol seen))))))))
(define (lolly-validate-grammar start tokens rules nonterms)
  (let ((declared (lolly-union tokens nonterms)))
    (for-each
     (lambda (rule)
       (for-each
        (lambda (symbol)
          (if (not (member symbol declared))
              (error "undefined grammar symbol" symbol)))
        (vector-ref rule 1)))
     rules)
    (let ((reachable (lolly-reachable-symbols start rules)))
      (for-each
       (lambda (nonterm)
         (if (not (member nonterm reachable))
             (error "unreachable non-terminal" nonterm)))
       nonterms))))

;; each rule stores its lhs its rhs its precedence its action and its source number.
(define (lolly-read-grammar form)
  (if (or (null? form) (not (eq? (car form) 'grammar)))
      (error "grammar must begin with (grammar ... )"))
  (let ((tokens '()) (start #f) (prec '()) (rules '()))
    (for-each
     (lambda (c)
       (case (car c)
         ((tokens) (set! tokens (cdr c)))
         ((start) (set! start (cadr c)))
         ((precedence)
          (let loop ((ps (cdr c)) (level 1))
            (if (pair? ps)
                (begin
                  (if (not (memq (caar ps) '(left right nonassoc)))
                      (error "bad associativity"))
                  (for-each (lambda (x) (set! prec (cons (cons x (cons level (caar ps))) prec)))
                            (cdar ps))
                  (loop (cdr ps) (+ level 1))))))
         ((rules)
          (for-each
           (lambda (r)
             (let* ((lhs (car r)) (rhs (cadr r)) (opts (cddr r))
                    (p #f) (a #f))
               (let scan ((xs opts))
                 (if (pair? xs)
                     (cond ((and (eq? (car xs) 'prec) (pair? (cdr xs)))
                            (set! p (cadr xs)) (scan (cddr xs)))
                           ((and (eq? (car xs) 'action) (pair? (cdr xs)))
                            (set! a (cadr xs)) (scan (cddr xs)))
                           (else (error "bad rule option")))))
               (set! rules (append rules (list (vector lhs rhs p a (length rules)))))))
           (cdr c)))
         (else (error "unknown grammar clause"))))
     (cdr form))
    (if (null? rules) (error "grammar has no rules"))
    (if (not start) (set! start (vector-ref (car rules) 0)))
    (let* ((nonterms (lolly-set-add start
                    (let loop ((rs rules) (out '()))
                      (if (null? rs) out
                          (loop (cdr rs) (lolly-set-add (vector-ref (car rs) 0) out))))))
           (symbols (let loop ((rs rules) (out tokens))
                      (if (null? rs) out
                          (loop (cdr rs) (lolly-union (vector-ref (car rs) 1) out)))))
           (terms (lolly-filter (lambda (x) (not (member x nonterms))) symbols)))
      (lolly-validate-grammar start tokens rules nonterms)
      (if (not (member '$end terms)) (set! terms (append terms (list '$end))))
      (vector tokens start prec rules nonterms terms))))

(define (lolly-grammar-file path)
  (call-with-input-file path (lambda (p) (lolly-read-grammar (read p)))))
(define (lolly-item-key i) (list (vector-ref i 0) (vector-ref i 1)))
(define (lolly-item-member i xs)
  (lolly-any (lambda (x) (and (equal? (lolly-item-key i) (lolly-item-key x))
                              (equal? (vector-ref i 2) (vector-ref x 2)))) xs))
(define (lolly-item-find i xs)
  (cond ((null? xs) #f)
        ((equal? (lolly-item-key i) (lolly-item-key (car xs))) (car xs))
        (else (lolly-item-find i (cdr xs)))))
(define (lolly-first-seq seq first nullable look)
  (let loop ((xs seq) (out '()))
    (if (null? xs) (lolly-set-add look out)
        (let ((f (lolly-ref (car xs) first '())))
          (if (lolly-ref (car xs) nullable #f)
              (loop (cdr xs) (lolly-union f out))
              (lolly-union f out))))))

(define (lolly-build grammar)
  (let* ((start (vector-ref grammar 1)) (user-rules (vector-ref grammar 3))
         (nonterms (vector-ref grammar 4)) (terms (vector-ref grammar 5))
         (rules (cons (vector '$start (list start) #f #f -1) user-rules))
         (first (map (lambda (x) (cons x (if (member x terms) (list x) '())))
                     (lolly-union terms nonterms)))
         (nullable (map (lambda (x) (cons x #f)) nonterms)))
    (let fixed ()
      (let ((changed #f))
        (for-each
         (lambda (r)
           (let ((lhs (vector-ref r 0)) (rhs (vector-ref r 1)))
             (if (or (null? rhs) (lolly-all (lambda (x) (lolly-ref x nullable #f)) rhs))
                 (if (not (lolly-ref lhs nullable #f))
                     (begin (set! nullable (lolly-put lhs #t nullable)) (set! changed #t))))
             (let ((old (lolly-ref lhs first '()))
                   (new (lolly-first-seq rhs first nullable #f)))
               (if (not (lolly-subset new old))
                   (begin (set! first (lolly-put lhs (lolly-union new old) first))
                          (set! changed #t)))))) rules)
        (if changed (fixed))))
    (letrec ((closure
              (lambda (items)
                (let loop ((work items) (out items))
                  (if (null? work) out
                      (let* ((item (car work))
                             (rule (list-ref rules (vector-ref item 0)))
                             (rhs (vector-ref rule 1))
                             (dot (vector-ref item 1)))
                        (if (or (>= dot (length rhs))
                                (not (member (list-ref rhs dot) nonterms)))
                            (loop (cdr work) out)
                            (let* ((symbol (list-ref rhs dot))
                                   (lookaheads
                                    (lolly-first-seq
                                     (append (list-tail rhs (+ dot 1))
                                             (vector-ref item 2))
                                     first nullable #f)))
                              (let add ((rs rules) (number 0) (pending (cdr work)) (result out))
                                (if (null? rs) (loop pending result)
                                    (if (eq? (vector-ref (car rs) 0) symbol)
                                        (let* ((new-item (vector number 0 lookaheads))
                                               (old-item (lolly-item-find new-item result)))
                                          (if old-item
                                              (let ((merged (lolly-union (vector-ref new-item 2)
                                                                          (vector-ref old-item 2))))
                                                (if (equal? merged (vector-ref old-item 2))
                                                    (add (cdr rs) (+ number 1) pending result)
                                                    (begin
                                                      (vector-set! old-item 2 merged)
                                                      (add (cdr rs) (+ number 1)
                                                           (cons old-item pending) result))))
                                              (add (cdr rs) (+ number 1)
                                                   (cons new-item pending)
                                                   (cons new-item result))))
                                        (add (cdr rs) (+ number 1) pending result))))))))))))
      (set! lolly-build-states
        (list (closure
           (cons (vector 0 0 (list '$end))
             (let seed ((rs (cdr rules)) (n 1) (out '()))
               (if (null? rs) out
               (if (eq? (vector-ref (car rs) 0) start)
                   (seed (cdr rs) (+ n 1)
                     (cons (vector n 0 (list '$end)) out))
                   (seed (cdr rs) (+ n 1) out))))))))
      (set! lolly-build-transitions '())
      (let scan ((n 0))
        (if (< n (length lolly-build-states))
            (begin
              (for-each
               (lambda (sym)
                 (let ((ns (closure
                            (map
                             (lambda (i) (vector (vector-ref i 0) (+ (vector-ref i 1) 1)
                                                   (vector-ref i 2)))
                             (lolly-filter
                              (lambda (i)
                                (let* ((r (list-ref rules (vector-ref i 0)))
                                       (rhs (vector-ref r 1)) (d (vector-ref i 1)))
                                  (and (< d (length rhs)) (eq? (list-ref rhs d) sym))))
                              (list-ref lolly-build-states n))))))
                   (if (not (null? ns))
                       (let ((old (lolly-index ns lolly-build-states)))
                         (if old (set! lolly-build-transitions (cons (list n sym old) lolly-build-transitions))
                             (begin (set! lolly-build-states (append lolly-build-states (list ns)))
                                    (set! lolly-build-transitions (cons (list n sym (- (length lolly-build-states) 1)) lolly-build-transitions))))))))
               (let loop ((is (list-ref lolly-build-states n)) (out '()))
                 (if (null? is) out
                     (let* ((i (car is)) (r (list-ref rules (vector-ref i 0)))
                            (rhs (vector-ref r 1)) (d (vector-ref i 1)))
                       (if (>= d (length rhs)) (loop (cdr is) out)
                           (loop (cdr is) (lolly-set-add (list-ref rhs d) out)))))))
              (scan (+ n 1)))))
      (vector rules nonterms terms (vector-ref grammar 2) lolly-build-states lolly-build-transitions))))

;; merge states with equal lr(0) cores while retaining their combined lookaheads.
(define (lolly-merge machine)
  (let* ((rules (vector-ref machine 0)) (states (vector-ref machine 4))
         (trans (vector-ref machine 5)) (groups '()))
    (for-each (lambda (s)
                (let ((core (map lolly-item-key s)) (g (lolly-assoc (map lolly-item-key s) groups)))
                  (if g (set-cdr! g (cons s (cdr g)))
                      (set! groups (cons (cons core (list s)) groups))))) states)
    (set! groups (reverse groups))
    (let ((state-id '()) (n 0))
      (for-each
       (lambda (g)
         (let find ((ss states) (index 0))
           (if (pair? ss)
               (if (equal? (map lolly-item-key (car ss)) (car g))
                   (begin (set! state-id (cons (cons index n) state-id))
                          (find (cdr ss) (+ index 1)))
                   (find (cdr ss) (+ index 1)))))
         (set! n (+ n 1)))
       groups)
      (let ((merged (map (lambda (g)
                           (let out ((items '()) (ss (cdr g)))
                             (if (null? ss) items
                                 (out (lolly-fold-left
                                       (lambda (o i)
                                         (let ((old (lolly-assoc (lolly-item-key i) o)))
                                           (if old (lolly-put (lolly-item-key i) (lolly-union (vector-ref i 2) (cdr old)) o)
                                               (cons (cons (lolly-item-key i) (vector-ref i 2)) o))))
                                       items (car ss)) (cdr ss))))) groups)))
        (vector rules (vector-ref machine 1) (vector-ref machine 2) (vector-ref machine 3)
                merged (map (lambda (t) (list (cdr (lolly-assoc (list-ref t 0) state-id))
                                               (list-ref t 1) (cdr (lolly-assoc (list-ref t 2) state-id)))) trans))))))

(define (lolly-tables machine)
  (let* ((m (lolly-merge machine)) (rules (vector-ref m 0)) (nonterms (vector-ref m 1))
         (prec (vector-ref m 3)) (states (vector-ref m 4)) (trans (vector-ref m 5))
         (actions '()) (gotos '()))
    (define (rule-precedence rule)
      (or (lolly-assoc (vector-ref rule 2) prec)
          (let scan ((symbols (reverse (vector-ref rule 1))))
            (if (null? symbols) #f
                (or (lolly-assoc (car symbols) prec) (scan (cdr symbols)))))))
    (for-each (lambda (t) (if (member (cadr t) nonterms)
                              (set! gotos (lolly-put (list (car t) (cadr t)) (caddr t) gotos))
                              (set! actions (lolly-put (list (car t) (cadr t)) (cons 'shift (caddr t)) actions)))) trans)
    (let resolve ((ss states) (s 0))
      (if (pair? ss)
          (begin
            (for-each
             (lambda (entry)
              (let* ((key (car entry)) (las (cdr entry)) (r (list-ref rules (car key)))
                  (rhs (vector-ref r 1)) (complete (= (cadr key) (length rhs))))
                (if complete
                 (let ((candidate (if (= (car key) 0) 'accept (cons 'reduce (car key)))))
                 (for-each
                  (lambda (la)
                    (let* ((k (list s la)) (old (lolly-assoc k actions))
                            (tp (lolly-assoc la prec))
                            (rp (rule-precedence r)))
                          (if (and old (not (equal? (cdr old) candidate)) tp rp)
                           (let ((token-level (car (cdr tp)))
                              (rule-level (car (cdr rp)))
                              (associativity (cdr (cdr tp))))
                             (if (or (> token-level rule-level)
                               (and (= token-level rule-level)
                                 (eq? associativity 'right)))
                              (set! candidate (cdr old))
                              (if (and (= token-level rule-level)
                                 (eq? associativity 'nonassoc))
                               (set! candidate '(error))))))
                      (set! actions (lolly-put k candidate actions))))
                  las)))))
             (map (lambda (i) (cons (car i) (cdr i))) (list-ref states s)))
            (resolve (cdr ss) (+ s 1)))))
    (vector actions gotos rules)))

(define (lolly-action-procedure action)
  (if (procedure? action) action (eval action (current-module))))
(define (lolly-expected-tokens state actions)
  (let loop ((entries actions) (out '()))
    (if (null? entries) (reverse out)
        (if (= state (car (car (car entries))))
            (loop (cdr entries) (cons (cadr (car (car entries))) out))
            (loop (cdr entries) out)))))

(define (lolly-parse tables tokens)
  (let ((actions (vector-ref tables 0)) (gotos (vector-ref tables 1))
        (rules (vector-ref tables 2)) (stack '(0)) (vals '())
        (input (append tokens (list (cons '$end #f)))))
    (let loop ((input input))
      (let* ((tok (car input)) (a (lolly-assoc (list (car stack) (car tok)) actions)))
        (if (not a)
          (error "syntax error" (car tok)
               (lolly-expected-tokens (car stack) actions))
            (let ((op (cdr a)))
              (cond ((eq? op 'accept) (if (null? vals) #f (car vals)))
                    ((eq? op 'error) (error "nonassociative syntax error" (car tok)))
                    ((eq? (car op) 'shift)
                     (set! stack (cons (cdr op) stack))
                     (set! vals (cons (cdr tok) vals))
                     (loop (cdr input)))
                    ((eq? (car op) 'reduce)
                     (let* ((r (list-ref rules (cdr op))) (n (length (vector-ref r 1)))
                            (argv (let take ((x vals) (i n) (o '()))
                                    (if (= i 0) o
                                        (take (cdr x) (- i 1) (cons (car x) o)))))
                            (v (if (vector-ref r 3)
                              (apply (lolly-action-procedure (vector-ref r 3)) argv)
                              (if (null? argv) #f (car argv))))
                            (base (list-tail stack n)) (g (lolly-assoc (list (car base) (vector-ref r 0)) gotos)))
                       (if (not g) (error "missing goto" (vector-ref r 0)))
                       (set! stack (cons (cdr g) base))
                       (set! vals (cons v (list-tail vals n)))
                       (loop input))))))))))

(define (lolly-parser grammar)
  (lolly-tables (lolly-build (if (vector? grammar) grammar (lolly-read-grammar grammar)))))
(define (lolly-inspect grammar)
  (let* ((machine (lolly-build (if (vector? grammar) grammar (lolly-read-grammar grammar))))
         (tables (lolly-tables machine)))
    (display (list 'version lolly-version
                   'canonical-states (length (vector-ref machine 4))
                   'lalr-states (length (vector-ref (lolly-merge machine) 4))
                   'actions (length (vector-ref tables 0))
                   'gotos (length (vector-ref tables 1))))
    (newline)))
(define (lolly-generate grammar output)
  (let ((tables (lolly-parser grammar)))
    (call-with-output-file output
      (lambda (p)
        (display ";;; generated by lolly and requiring src/lolly-core.scm.\n" p)
        (write `(define lolly-generated-parser (lambda (tokens) (lolly-parse ',tables tokens))) p)
        (newline p)))))
(define (lolly-main args)
  (if (< (length args) 2) (begin (display "usage: bin/lolly [--version | --inspect GRAMMAR | GRAMMAR [OUTPUT]]\n") 1)
      (begin
        (if (equal? (cadr args) "--version")
            (begin (display lolly-version) (newline))
            (if (equal? (cadr args) "--inspect")
            (lolly-inspect (lolly-grammar-file (caddr args)))
            (if (> (length args) 2) (lolly-generate (lolly-grammar-file (cadr args)) (caddr args))
                (write (lolly-parser (lolly-grammar-file (cadr args)))))))
        (newline) 0)))
(if (and (defined? 'command-line) (pair? (command-line))
         (equal? (car (command-line)) "lolly.scm")) (exit (lolly-main (command-line))))